---
# MIT License
# Copyright (c) 2017 Nicola Worthington <nicolaw@tfb.net>

version: "3"
services:
  wow-db:
    image: "mariadb:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-okgreat}"
      MYSQL_USER: "${DB_USERNAME:-trinity}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-trinity}"
      LOCALIP: "${LOCALIP:-192.168.0.5}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${LOCALIP:-192.168.0.5}"]
      timeout: "20s"
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - ../artifacts/mysql:/var/lib/mysql
      - ../artifacts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  authserver:
    build: authserver
    environment:
      DB_HOST: "${DB_HOST:-wow-db}"
      DB_PORT: "${DB_PORT:-3306}"
    depends_on:
      - wow-db
    links:
      - wow-db:mysql
    ports:
      - "3724:3724"
    volumes:
      - ../artifacts/etc:/opt/trinitycore/etc
  worldserver:
    build: worldserver
    environment:
      DB_HOST: "${DB_HOST:-wow-db}"
      DB_PORT: "${DB_PORT:-3306}"
    healthcheck:
      test: ["CMD", "./tcadmin",
       "--soaphost=192.168.0.5",
       "--soapport=7878",
       "--soapuser=trinity",
       "--soappass=trinity"]
      interval: "60s"
      timeout: "15s"
      retries: 3
    depends_on:
      - wow-db
    links:
      - wow-db:mysql
    ports:
      - "8085:8085"
      - "3443:3443"
      - "7878:7878"
    volumes:
      - ../artifacts/etc:/opt/trinitycore/etc
      - ../artifacts/mapdata:/opt/trinitycore/mapdata
      - ../artifacts/sql:/opt/trinitycore/sql
  tcjsonapi:
    build: tcjsonapi
    environment:
      DB_HOST: "${DB_HOST:-wow-db}"
      DB_PORT: "${DB_PORT:-3306}"
      DB_USERNAME: "${DB_USERNAME:-trinity}"
      DB_PASSWORD: "${DB_PASSWORD:-trinity}"
      BIND_IP: "0.0.0.0"
      BIND_PORT: "80"
    depends_on:
      - wow-db
    links:
      - wow-db:mysql
    ports:
      - "8081:80"
  keira2:
    build: keira2
    environment:
      ServerName: "192.168.0.5"
      TC_JSON_API_PORT: "8081"
    healthcheck:
          test: ["CMD", "curl", "-sSLIf http://192.168.0.5:80/Keira2/index.html"]
          interval: "60s"
          timeout: "15s"
          retries: 3
    depends_on:
      - tcjsonapi
    ports:
      - "8082:80"

# TODO: aowow is still a work in progress.
#
#  aowow:
#    build: aowow
#    environment:
#      DB_HOST: "${DB_HOST:-wow-db}"
#      DB_USERNAME: "${DB_USERNAME:-trinity}"
#      DB_PASSWORD: "${DB_USERNAME:-trinity}"
#      DB_AOWOW: "${DB_AOWOW:-aowowdb}"
#    volumes:
#      - ../artifacts/mpqdata:/usr/local/aowow/setup/mpqdata
#      - ../World_of_Warcraft:/usr/local/World_of_Warcraft:ro
#    depends_on:
#      - wow-db
#    links:
#      - wow-db:mysql
#    ports:
#      - "8083:80"
#  aowow-db:
#    image: mysql:5.7
#    volumes:
#      - db_data:/var/lib/mysql
#    #restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: aowowdbroot
#      MYSQL_USER: aowowdb
#      MYSQL_PASSWORD: aowowdb
#    ports:
#      - "8084:3306"